#!/bin/bash
#
# File: 	install_only_nagios_pugins
# Author: 	Zach Jetson
# Date:		2-15-17
# Requires:	CentOS 6
#
# Nagios Pluins Setup script
# This script will install only common Nagios Plugins.
# 

echo "Updating package cache"
yum update -y

echo "Installing epel-release"
yum install -y epel-release

echo "Installing nagios and plugins"
yum --enablerepo=epel -y install nagios-plugins nagios-plugins-check-updates nagios-plugins-disk nagios-plugins-http nagios-plugins-rpc nagios-plugins-mailq nagios-plugins-mysql nagios-plugins-log nagios-plugins-uptime nagios-plugins-users nagios-plugins-load nagios-plugins-ldap nagios-plugins-swap

echo "Adding check_cpu python script"
mkdir -p /usr/local/nagios/libexec
SCRIPT_PATH="/usr/local/nagios/libexec/check_cpu"
curl -L "https://raw.githubusercontent.com/subfission/centos-installers/master/resources/check_cpu" > $SCRIPT_PATH

echo "Making script executable"
chmod +x $SCRIPT_PATH

echo "Setting permissions"
chown root:nagios $SCRIPT_PATH

echo "Testing"
$SCRIPT_PATH
echo
echo
echo "If you did not see an error, the install complete successfully."
